<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class MediaTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('media')->delete();
        
        \DB::table('media')->insert(array (
            0 => 
            array (
                'id' => 1,
                'model_type' => 'App\\Models\\Product',
                'model_id' => 1,
                'uuid' => '5403ef8e-61fa-458d-94c0-b446b5f7415b',
                'collection_name' => 'images',
                'name' => 'Auramaster',
                'file_name' => 'Auramaster.jpg',
                'mime_type' => 'image/jpeg',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 843097,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2026-05-10 09:29:27',
                'updated_at' => '2026-05-10 09:29:27',
            ),
            1 => 
            array (
                'id' => 2,
                'model_type' => 'App\\Models\\Product',
                'model_id' => 2,
                'uuid' => '709fffc6-5b23-4ad5-81e2-1f24bee9de7a',
                'collection_name' => 'images',
                'name' => 'Echoforge',
                'file_name' => 'Echoforge.jpg',
                'mime_type' => 'image/webp',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 17244,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2026-05-10 09:29:27',
                'updated_at' => '2026-05-10 09:29:27',
            ),
            2 => 
            array (
                'id' => 3,
                'model_type' => 'App\\Models\\Product',
                'model_id' => 3,
                'uuid' => '7f989567-decb-48b6-9d1f-00d5e7b2e68d',
                'collection_name' => 'images',
                'name' => 'Sonicprism',
                'file_name' => 'Sonicprism.jpg',
                'mime_type' => 'image/jpeg',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 152936,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2026-05-10 09:29:27',
                'updated_at' => '2026-05-10 09:29:27',
            ),
            3 => 
            array (
                'id' => 4,
                'model_type' => 'App\\Models\\Product',
                'model_id' => 4,
                'uuid' => '32192336-7406-40d1-908b-4643ed105872',
                'collection_name' => 'images',
                'name' => 'Resonanceover',
                'file_name' => 'Resonanceover.jpg',
                'mime_type' => 'image/webp',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 8010,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2026-05-10 09:29:27',
                'updated_at' => '2026-05-10 09:29:27',
            ),
            4 => 
            array (
                'id' => 5,
                'model_type' => 'App\\Models\\Product',
                'model_id' => 5,
                'uuid' => '091648fd-d82a-4386-946f-2af8ba415827',
                'collection_name' => 'images',
                'name' => 'Obsidianvelvet',
                'file_name' => 'Obsidianvelvet.jpg',
                'mime_type' => 'image/webp',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 4796,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2026-05-10 09:29:27',
                'updated_at' => '2026-05-10 09:29:27',
            ),
            5 => 
            array (
                'id' => 6,
                'model_type' => 'App\\Models\\Product',
                'model_id' => 6,
                'uuid' => '2859031a-65b7-43ab-965b-2e6949814710',
                'collection_name' => 'images',
                'name' => 'Aegisvanguard',
                'file_name' => 'Aegisvanguard.jpg',
                'mime_type' => 'image/webp',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 9676,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2026-05-10 09:29:27',
                'updated_at' => '2026-05-10 09:29:27',
            ),
            6 => 
            array (
                'id' => 7,
                'model_type' => 'App\\Models\\Product',
                'model_id' => 7,
                'uuid' => '3ab51dd6-960f-46f8-b111-a63a5ddbc089',
                'collection_name' => 'images',
                'name' => 'Onyxcarbon15pro',
                'file_name' => 'Onyxcarbon15pro.jpg',
                'mime_type' => 'image/webp',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 10394,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2026-05-10 09:29:27',
                'updated_at' => '2026-05-10 09:29:27',
            ),
            7 => 
            array (
                'id' => 8,
                'model_type' => 'App\\Models\\Product',
                'model_id' => 8,
                'uuid' => '1ed0053b-f1e3-479e-810b-592f75e5ed5a',
                'collection_name' => 'images',
                'name' => 'Leatherartisanipad',
                'file_name' => 'Leatherartisanipad.jpg',
                'mime_type' => 'image/webp',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 4754,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2026-05-10 09:29:27',
                'updated_at' => '2026-05-10 09:29:27',
            ),
            8 => 
            array (
                'id' => 9,
                'model_type' => 'App\\Models\\Product',
                'model_id' => 9,
                'uuid' => 'debe62a1-5d93-453c-9f4f-591bf99667ff',
                'collection_name' => 'images',
                'name' => 'Obsidianshieldmacbook',
                'file_name' => 'Obsidianshieldmacbook.jpg',
                'mime_type' => 'image/webp',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 6210,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2026-05-10 09:29:27',
                'updated_at' => '2026-05-10 09:29:27',
            ),
            9 => 
            array (
                'id' => 10,
                'model_type' => 'App\\Models\\Product',
                'model_id' => 10,
                'uuid' => '9d0e8687-be05-4053-baba-8b51c4a58747',
                'collection_name' => 'images',
                'name' => 'Velvettouchtech',
                'file_name' => 'Velvettouchtech.jpg',
                'mime_type' => 'image/webp',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 11418,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2026-05-10 09:29:27',
                'updated_at' => '2026-05-10 09:29:27',
            ),
            10 => 
            array (
                'id' => 11,
                'model_type' => 'App\\Models\\Product',
                'model_id' => 11,
                'uuid' => '57946ac8-ce6c-4cc3-a917-e153dac05595',
                'collection_name' => 'images',
                'name' => 'Nexusquantum12in1',
                'file_name' => 'Nexusquantum12in1.jpg',
                'mime_type' => 'image/jpeg',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 24790,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2026-05-10 09:29:27',
                'updated_at' => '2026-05-10 09:29:27',
            ),
            11 => 
            array (
                'id' => 12,
                'model_type' => 'App\\Models\\Product',
                'model_id' => 12,
                'uuid' => '2d453001-9126-454b-80fa-627f61d93b8d',
                'collection_name' => 'images',
                'name' => 'Choronoswireless',
                'file_name' => 'Choronoswireless.jpg',
                'mime_type' => 'image/jpeg',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 7586,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2026-05-10 09:29:27',
                'updated_at' => '2026-05-10 09:29:27',
            ),
            12 => 
            array (
                'id' => 13,
                'model_type' => 'App\\Models\\Product',
                'model_id' => 13,
                'uuid' => '019be945-9d3e-4f09-af17-6a10d7c88235',
                'collection_name' => 'images',
                'name' => 'Omnicore140w',
                'file_name' => 'Omnicore140w.jpg',
                'mime_type' => 'image/webp',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 6174,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2026-05-10 09:29:27',
                'updated_at' => '2026-05-10 09:29:27',
            ),
            13 => 
            array (
                'id' => 14,
                'model_type' => 'App\\Models\\Product',
                'model_id' => 14,
                'uuid' => '1a35f0d7-c690-46f9-99b4-a6397dc19fad',
                'collection_name' => 'images',
                'name' => 'carbonbraided',
                'file_name' => 'carbonbraided.jpg',
                'mime_type' => 'image/webp',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 54974,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2026-05-10 09:29:27',
                'updated_at' => '2026-05-10 09:29:27',
            ),
            14 => 
            array (
                'id' => 15,
                'model_type' => 'App\\Models\\Product',
                'model_id' => 15,
                'uuid' => 'bb2cb922-719e-4a00-aae3-93211e846069',
                'collection_name' => 'images',
                'name' => 'Solarflarepowerbank',
                'file_name' => 'Solarflarepowerbank.jpg',
                'mime_type' => 'image/webp',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 6990,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2026-05-10 09:29:27',
                'updated_at' => '2026-05-10 09:29:27',
            ),
            15 => 
            array (
                'id' => 16,
                'model_type' => 'App\\Models\\Product',
                'model_id' => 16,
                'uuid' => '525fb4bb-f6b6-405f-8d93-a24a333bebbd',
                'collection_name' => 'images',
                'name' => 'RetinaX6kPro',
                'file_name' => 'RetinaX6kPro.jpg',
                'mime_type' => 'image/jpeg',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 32929,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2026-05-10 09:29:27',
                'updated_at' => '2026-05-10 09:29:27',
            ),
            16 => 
            array (
                'id' => 17,
                'model_type' => 'App\\Models\\Product',
                'model_id' => 17,
                'uuid' => 'd828eae9-cf7d-4ad2-9eb9-16734ba6bc92',
                'collection_name' => 'images',
                'name' => 'Horizoncurved',
                'file_name' => 'Horizoncurved.jpg',
                'mime_type' => 'image/webp',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 9070,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2026-05-10 09:29:27',
                'updated_at' => '2026-05-10 09:29:27',
            ),
            17 => 
            array (
                'id' => 18,
                'model_type' => 'App\\Models\\Product',
                'model_id' => 18,
                'uuid' => '953bf42b-05ed-4cea-a5ed-5c8c4da707a7',
                'collection_name' => 'images',
                'name' => 'Prismportable',
                'file_name' => 'Prismportable.jpg',
                'mime_type' => 'image/jpeg',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 5923,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2026-05-10 09:29:27',
                'updated_at' => '2026-05-10 09:29:27',
            ),
            18 => 
            array (
                'id' => 19,
                'model_type' => 'App\\Models\\Product',
                'model_id' => 19,
                'uuid' => '49bcf448-4107-43d9-b274-0d52ec57126d',
                'collection_name' => 'images',
                'name' => 'obsidianframeless',
                'file_name' => 'obsidianframeless.jpg',
                'mime_type' => 'image/webp',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 31466,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2026-05-10 09:29:27',
                'updated_at' => '2026-05-10 09:29:27',
            ),
            19 => 
            array (
                'id' => 20,
                'model_type' => 'App\\Models\\Product',
                'model_id' => 20,
                'uuid' => '79a7de08-bcba-4486-898b-510da9a825e9',
                'collection_name' => 'images',
                'name' => 'Visionarystudiodisplay8K',
                'file_name' => 'Visionarystudiodisplay8K.jpg',
                'mime_type' => 'image/jpeg',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 420726,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2026-05-10 09:29:27',
                'updated_at' => '2026-05-10 09:29:27',
            ),
            20 => 
            array (
                'id' => 21,
                'model_type' => 'App\\Models\\Category',
                'model_id' => 1,
                'uuid' => 'c6dd9d31-45f5-4321-9785-0e5ee381f3d1',
                'collection_name' => 'images',
                'name' => 'Auramaster',
                'file_name' => 'Auramaster.jpg',
                'mime_type' => 'image/jpeg',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 843097,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2026-05-10 09:29:27',
                'updated_at' => '2026-05-10 09:29:27',
            ),
            21 => 
            array (
                'id' => 22,
                'model_type' => 'App\\Models\\Category',
                'model_id' => 2,
                'uuid' => '7a3db5d9-7ba4-4ed4-9b9a-7d77363c0c1f',
                'collection_name' => 'images',
                'name' => 'Aegisvanguard',
                'file_name' => 'Aegisvanguard.jpg',
                'mime_type' => 'image/webp',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 9676,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2026-05-10 09:29:27',
                'updated_at' => '2026-05-10 09:29:27',
            ),
            22 => 
            array (
                'id' => 23,
                'model_type' => 'App\\Models\\Category',
                'model_id' => 3,
                'uuid' => '5dbb0166-9e03-4ea7-83d6-9c1f6b78a32d',
                'collection_name' => 'images',
                'name' => 'Nexusquantum12in1',
                'file_name' => 'Nexusquantum12in1.jpg',
                'mime_type' => 'image/jpeg',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 24790,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2026-05-10 09:29:27',
                'updated_at' => '2026-05-10 09:29:27',
            ),
            23 => 
            array (
                'id' => 24,
                'model_type' => 'App\\Models\\Category',
                'model_id' => 4,
                'uuid' => 'a52ed05f-9ee6-46d1-9602-b941439932e1',
                'collection_name' => 'images',
                'name' => 'RetinaX6kPro',
                'file_name' => 'RetinaX6kPro.jpg',
                'mime_type' => 'image/jpeg',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 32929,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2026-05-10 09:29:27',
                'updated_at' => '2026-05-10 09:29:27',
            ),
        ));
        
        
    }
}