<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class ProductsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('products')->delete();
        
        \DB::table('products')->insert(array (
            0 => 
            array (
                'id' => 1,
                'name' => 'Aura Master Headphone - Limited Obsidian',
                'slug' => 'aura-master-headphone-limited-obsidian',
                'description' => 'Tai nghe over-ear với công nghệ chống ồn chủ động kép. Lớp hoàn thiện Obsidian mờ sang trọng.',
                'detail' => NULL,
                'image' => 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?q=80&w=800&auto=format&fit=crop',
                'price' => 499.0,
                'sale_price' => 449.0,
                'quantity' => 0,
                'view' => 1,
                'category_id' => 1,
                'featured' => 1,
                'created_at' => '2026-05-04 07:00:03',
                'updated_at' => '2026-05-10 07:43:43',
            ),
            1 => 
            array (
                'id' => 2,
                'name' => 'Echo Forge Wireless Earbuds',
                'slug' => 'echo-forge-wireless-earbuds',
                'description' => 'Tai nghe TWS vỏ nhôm xước nguyên khối, âm thanh Hi-Res Audio chứng nhận.',
                'detail' => NULL,
                'image' => 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?q=80&w=800&auto=format&fit=crop',
                'price' => 249.0,
                'sale_price' => NULL,
                'quantity' => 0,
                'view' => 0,
                'category_id' => 1,
                'featured' => 0,
                'created_at' => '2026-05-04 07:00:03',
                'updated_at' => '2026-05-04 07:00:03',
            ),
            2 => 
            array (
                'id' => 3,
                'name' => 'Sonic Prism Soundbar',
                'slug' => 'sonic-prism-soundbar',
                'description' => 'Loa thanh 7.1.4 Dolby Atmos với lưới tản nhiệt mạ vàng hồng 18K.',
                'detail' => NULL,
                'image' => 'https://images.unsplash.com/photo-1545454675-3531b543be5d?q=80&w=800&auto=format&fit=crop',
                'price' => 899.0,
                'sale_price' => 799.0,
                'quantity' => 0,
                'view' => 0,
                'category_id' => 1,
                'featured' => 1,
                'created_at' => '2026-05-04 07:00:03',
                'updated_at' => '2026-05-04 07:00:03',
            ),
            3 => 
            array (
                'id' => 4,
                'name' => 'Resonance Over-Ear Studio',
                'slug' => 'resonance-over-ear-studio',
                'description' => 'Tai nghe kiểm âm với màng loa Graphene, đệm tai bọc da Cừu thủ công.',
                'detail' => NULL,
                'image' => 'https://images.unsplash.com/photo-1583394838336-acd977736f90?q=80&w=800&auto=format&fit=crop',
                'price' => 599.0,
                'sale_price' => NULL,
                'quantity' => 0,
                'view' => 0,
                'category_id' => 1,
                'featured' => 0,
                'created_at' => '2026-05-04 07:00:03',
                'updated_at' => '2026-05-04 07:00:03',
            ),
            4 => 
            array (
                'id' => 5,
                'name' => 'Obsidian Velvet IEMs',
                'slug' => 'obsidian-velvet-iems',
                'description' => 'Tai nghe In-Ear Monitor đúc custom từ đá Obsidian đen tuyền.',
                'detail' => NULL,
                'image' => 'https://images.unsplash.com/photo-1598331668826-20cefac91461?q=80&w=800&auto=format&fit=crop',
                'price' => 349.0,
                'sale_price' => 299.0,
                'quantity' => 0,
                'view' => 0,
                'category_id' => 1,
                'featured' => 1,
                'created_at' => '2026-05-04 07:00:03',
                'updated_at' => '2026-05-04 07:00:03',
            ),
            5 => 
            array (
                'id' => 6,
                'name' => 'Aegis Vanguard Laptop Sleeve 16"',
                'slug' => 'aegis-vanguard-laptop-sleeve-16',
                'description' => 'Túi chống sốc da thật dập nổi kết hợp sợi carbon. Thiết kế phi tuyến tính độc bản.',
                'detail' => NULL,
                'image' => 'https://images.unsplash.com/photo-1600294037681-c80b4cb5b434?q=80&w=800&auto=format&fit=crop',
                'price' => 89.0,
                'sale_price' => NULL,
                'quantity' => 0,
                'view' => 0,
                'category_id' => 2,
                'featured' => 0,
                'created_at' => '2026-05-04 07:00:03',
                'updated_at' => '2026-05-04 07:00:03',
            ),
            6 => 
            array (
                'id' => 7,
                'name' => 'Onyx Carbon iPhone 15 Pro Case',
                'slug' => 'onyx-carbon-iphone-15-pro-case',
                'description' => 'Ốp lưng từ sợi Carbon thật kết hợp viền hợp kim Titantium mạ vàng đen.',
                'detail' => NULL,
                'image' => 'https://images.unsplash.com/photo-1586953208448-b95a79798f07?q=80&w=800&auto=format&fit=crop',
                'price' => 59.0,
                'sale_price' => 49.0,
                'quantity' => 0,
                'view' => 0,
                'category_id' => 2,
                'featured' => 1,
                'created_at' => '2026-05-04 07:00:03',
                'updated_at' => '2026-05-04 07:00:03',
            ),
            7 => 
            array (
                'id' => 8,
                'name' => 'Leather Artisan iPad Pro Folio',
                'slug' => 'leather-artisan-ipad-pro-folio',
                'description' => 'Bao da iPad khâu thủ công từ Ý, nhuộm màu đen sẫm Dark Atelier.',
                'detail' => NULL,
                'image' => 'https://images.unsplash.com/photo-1611532736597-de2d4265fba3?q=80&w=800&auto=format&fit=crop',
                'price' => 129.0,
                'sale_price' => NULL,
                'quantity' => 0,
                'view' => 1,
                'category_id' => 2,
                'featured' => 0,
                'created_at' => '2026-05-04 07:00:03',
                'updated_at' => '2026-05-04 07:01:56',
            ),
            8 => 
            array (
                'id' => 9,
                'name' => 'Obsidian Shield MacBook Shell',
                'slug' => 'obsidian-shield-macbook-shell',
                'description' => 'Ốp nhựa nhám mờ xuyên thấu siêu mỏng bảo vệ toàn diện cho MacBook.',
                'detail' => NULL,
                'image' => 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?q=80&w=800&auto=format&fit=crop',
                'price' => 79.0,
                'sale_price' => NULL,
                'quantity' => 0,
                'view' => 0,
                'category_id' => 2,
                'featured' => 0,
                'created_at' => '2026-05-04 07:00:03',
                'updated_at' => '2026-05-04 07:00:03',
            ),
            9 => 
            array (
                'id' => 10,
                'name' => 'Velvet Touch Tech Pouch',
                'slug' => 'velvet-touch-tech-pouch',
                'description' => 'Túi đựng phụ kiện công nghệ lót nhung bọc vải Kordura kháng nước.',
                'detail' => NULL,
                'image' => 'https://images.unsplash.com/photo-1544816155-12df9643f363?q=80&w=800&auto=format&fit=crop',
                'price' => 45.0,
                'sale_price' => 39.0,
                'quantity' => 0,
                'view' => 0,
                'category_id' => 2,
                'featured' => 0,
                'created_at' => '2026-05-04 07:00:03',
                'updated_at' => '2026-05-04 07:00:03',
            ),
            10 => 
            array (
                'id' => 11,
                'name' => 'Nexus Quantum Hub 12-in-1',
                'slug' => 'nexus-quantum-hub-12-in-1',
                'description' => 'Hub mở rộng với thân nhôm nguyên khối. Hỗ trợ xuất 2 màn hình 8K.',
                'detail' => NULL,
                'image' => 'https://images.unsplash.com/photo-1593640498182-31c70c8268f5?q=80&w=800&auto=format&fit=crop',
                'price' => 129.0,
                'sale_price' => NULL,
                'quantity' => 0,
                'view' => 0,
                'category_id' => 3,
                'featured' => 1,
                'created_at' => '2026-05-04 07:00:03',
                'updated_at' => '2026-05-04 07:00:03',
            ),
            11 => 
            array (
                'id' => 12,
                'name' => 'Chronos Wireless Charging Artifact',
                'slug' => 'chronos-wireless-charging-artifact',
                'description' => 'Đế sạc không dây 3 trong 1. Viền mạ vàng 18K và mặt kính Sapphire cường lực.',
                'detail' => NULL,
                'image' => 'https://images.unsplash.com/photo-1615526675159-e248c3021d3f?q=80&w=800&auto=format&fit=crop',
                'price' => 199.0,
                'sale_price' => 179.0,
                'quantity' => 0,
                'view' => 0,
                'category_id' => 3,
                'featured' => 1,
                'created_at' => '2026-05-04 07:00:03',
                'updated_at' => '2026-05-04 07:00:03',
            ),
            12 => 
            array (
                'id' => 13,
                'name' => 'OmniCore 140W GaN Charger',
                'slug' => 'omnicore-140w-gan-charger',
                'description' => 'Củ sạc siêu nhanh công nghệ GaN thế hệ mới, kích thước siêu nhỏ.',
                'detail' => NULL,
                'image' => 'https://images.unsplash.com/photo-1632213702157-1954848383a8?q=80&w=800&auto=format&fit=crop',
                'price' => 89.0,
                'sale_price' => NULL,
                'quantity' => 0,
                'view' => 0,
                'category_id' => 3,
                'featured' => 0,
                'created_at' => '2026-05-04 07:00:03',
                'updated_at' => '2026-05-04 07:00:03',
            ),
            13 => 
            array (
                'id' => 14,
                'name' => 'Carbon Braided Thunderbolt 4 Cable',
                'slug' => 'carbon-braided-thunderbolt-4-cable',
                'description' => 'Cáp bọc dù pha sợi carbon, băng thông 40Gbps siêu cấp.',
                'detail' => NULL,
                'image' => 'https://images.unsplash.com/photo-1624823183569-8395562d98dc?q=80&w=800&auto=format&fit=crop',
                'price' => 49.0,
                'sale_price' => NULL,
                'quantity' => 0,
                'view' => 0,
                'category_id' => 3,
                'featured' => 0,
                'created_at' => '2026-05-04 07:00:03',
                'updated_at' => '2026-05-04 07:00:03',
            ),
            14 => 
            array (
                'id' => 15,
                'name' => 'SolarFlare PowerBank 20000mAh',
                'slug' => 'solarflare-powerbank-20000mah',
                'description' => 'Pin dự phòng viền nhôm, tích hợp màn hình OLED hiển thị công suất.',
                'detail' => NULL,
                'image' => 'https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?q=80&w=800&auto=format&fit=crop',
                'price' => 149.0,
                'sale_price' => 129.0,
                'quantity' => 0,
                'view' => 0,
                'category_id' => 3,
                'featured' => 1,
                'created_at' => '2026-05-04 07:00:03',
                'updated_at' => '2026-05-04 07:00:03',
            ),
            15 => 
            array (
                'id' => 16,
                'name' => 'RetinaX 32" 6K Pro Display',
                'slug' => 'retinax-32-6k-pro-display',
                'description' => 'Màn hình chuyên đồ họa với độ phủ màu 100% DCI-P3, chân đế xoay 360.',
                'detail' => NULL,
                'image' => 'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?q=80&w=800&auto=format&fit=crop',
                'price' => 1999.0,
                'sale_price' => NULL,
                'quantity' => 0,
                'view' => 0,
                'category_id' => 4,
                'featured' => 1,
                'created_at' => '2026-05-04 07:00:03',
                'updated_at' => '2026-05-04 07:00:03',
            ),
            16 => 
            array (
                'id' => 17,
                'name' => 'Horizon Curved Ultrawide 49"',
                'slug' => 'horizon-curved-ultrawide-49',
                'description' => 'Màn hình cong vô cực 1000R, tấm nền QD-OLED cho sắc đen sâu thẳm.',
                'detail' => NULL,
                'image' => 'https://images.unsplash.com/photo-1616053351239-67d710d8e82d?q=80&w=800&auto=format&fit=crop',
                'price' => 1499.0,
                'sale_price' => 1299.0,
                'quantity' => 0,
                'view' => 0,
                'category_id' => 4,
                'featured' => 1,
                'created_at' => '2026-05-04 07:00:03',
                'updated_at' => '2026-05-04 07:00:03',
            ),
            17 => 
            array (
                'id' => 18,
                'name' => 'Prism Portable OLED 15.6"',
                'slug' => 'prism-portable-oled-15-6',
                'description' => 'Màn hình phụ di động siêu mỏng 4mm, kết nối chỉ cần 1 cáp Type-C.',
                'detail' => NULL,
                'image' => 'https://images.unsplash.com/photo-1588666309990-d68f08e3d4a6?q=80&w=800&auto=format&fit=crop',
                'price' => 399.0,
                'sale_price' => NULL,
                'quantity' => 0,
                'view' => 0,
                'category_id' => 4,
                'featured' => 0,
                'created_at' => '2026-05-04 07:00:03',
                'updated_at' => '2026-05-04 07:00:03',
            ),
            18 => 
            array (
                'id' => 19,
                'name' => 'Obsidian Frameless Monitor 27"',
                'slug' => 'obsidian-frameless-monitor-27',
                'description' => 'Màn hình viền siêu mỏng 4 cạnh, thiết kế nguyên khối phong cách Minimalist.',
                'detail' => NULL,
                'image' => 'https://images.unsplash.com/photo-1593640408182-31c70c8268f5?q=80&w=800&auto=format&fit=crop',
                'price' => 499.0,
                'sale_price' => 449.0,
                'quantity' => 0,
                'view' => 0,
                'category_id' => 4,
                'featured' => 0,
                'created_at' => '2026-05-04 07:00:03',
                'updated_at' => '2026-05-04 07:00:03',
            ),
            19 => 
            array (
                'id' => 20,
                'name' => 'Visionary Studio Display 8K',
                'slug' => 'visionary-studio-display-8k',
                'description' => 'Cực phẩm màn hình 8K đầu tiên trang bị MiniLED 4096 vùng sáng độc lập.',
                'detail' => NULL,
                'image' => 'https://images.unsplash.com/photo-1542744094-3a31f272c490?q=80&w=800&auto=format&fit=crop',
                'price' => 3499.0,
                'sale_price' => 3199.0,
                'quantity' => 0,
                'view' => 1,
                'category_id' => 4,
                'featured' => 1,
                'created_at' => '2026-05-04 07:00:03',
                'updated_at' => '2026-05-04 09:02:14',
            ),
        ));
        
        
    }
}